### ISSUE TITLE
Convert sites to markdown

### ISSUE THREAD

**Issue by DennisTobola** [gbv/coli-conc.gbv.de#18]
https://coli-conc.gbv.de/partners/  
https://coli-conc.gbv.de/terminologies/  
https://coli-conc.gbv.de/publications/software/  
https://coli-conc.gbv.de/publications/licenses/  
https://coli-conc.gbv.de/publications/kostypes/  
https://coli-conc.gbv.de/registry/ 

example: 33ce483236d214b4914b32eb6a388d68ab2eaf92
(html/php needs removing)?

**Comment by nichtich** [comment]
The dynamic elements can be created with jQuery as used at https://coli-conc.gbv.de/cocoda/

**Comment by stefandesu** [comment]
With the new site, everything's Markdown. :)
