### ISSUE TITLE
Equalize subheadings and links under "Services"

### ISSUE THREAD

**Issue by DennisTobola** [gbv/coli-conc.gbv.de#21]
Under the page "Services" there are subpoints, which aren't in the menu, likewise there are points in the menu, which aren't listed on the page directly.

![Screenshot_2019-06-25 coli-conc Services](https://user-images.githubusercontent.com/37077998/60096122-77869f80-9750-11e9-9792-f14b404b6f3c.png)

**Comment by stefandesu** [comment]
Becomes irrelevant with new website.
