### ISSUE TITLE
Replace /terminologies/ by dynamic list from BARTOC

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-conc.gbv.de#43]
Align the list at https://coli-conc.gbv.de/terminologies/ with BARTOC and add 

Listed In: http://bartoc.org/en/node/18926

so we can show an always updated list via the search http://bartoc.org/vocabularies?partOf=http://bartoc.org/en/node/18926. Ignore MARC and PICA unless it is empty in BARTOC (in doubt BARTOC is more up-to-date).

**Comment by stefandesu** [comment]
Should the list be fully dynamic, i.e. no more data is stored in this repository? We could also get the current list on each page build, so the page would remain fully static with no JavaScript.

The second option would be easy to implement as soon as all the relevant vocabularies are added to the registry in BARTOC.

**Comment by nichtich** [comment]
> The second option would be easy to implement as soon as all the relevant vocabularies are added to the registry in BARTOC.

I think this option is enough to work with.

**Comment by sabrinagaab** [comment]
[KOS_BARTOC.xlsx](https://github.com/gbv/coli-conc.gbv.de/files/6868252/KOS_BARTOC.xlsx)
The list under the given URL (https://coli-conc.gbv.de/terminologies/) is now in the KOS Registry in Bartoc (I added "Listed in" + URI for 32 entries). One entry of the given list could not be updated, see the issue above for more information.

**Comment by nichtich** [comment]
Ok, the list can now dynamically be queried from BARTOC: <http://bartoc.org/vocabularies?partOf=http://bartoc.org/en/node/18926>

**Comment by stefandesu** [comment]
Is [Systematik für Evangelische Büchereien (SEB)](http://bartoc.org/en/node/1324) (which is part of the current list on the website) not relevant anymore? I compared both lists and this is the only one missing.

**Comment by stefandesu** [comment]
I made the change now. You can adjust the API call [here](https://github.com/gbv/coli-conc.gbv.de/blob/main/_data/kos.js#L2). The list will be rebuilt every time the page is generated (i.e. on every push).

One remaining issue is that the list will be unavailable if the API call fails during page generation. Maybe we can have a static list as a backup.

**Comment by stefandesu** [comment]
> How can we enforce an update? Add a daily cronjob?

There should be a nightly update via a scheduled Github Action. As far as I can tell, it updated the site last night at 03:05:51 CET. Is there anything that you expected to be updated that wasn't? Maybe there is some other issue, e.g. with caching?

**Comment by nichtich** [comment]
Ok, then we can just wait a day if something has been changed in BARTOC (unless it is very urgent)

**Comment by stefandesu** [comment]
If you really want to rebuild the site without a new commit, you could go into the webhooks section in GitHub and simply resend the last webhook. ;)

**Comment by sabrinagaab** [comment]
[Ergänzung in BARTOC (2).md](https://github.com/gbv/coli-conc.gbv.de/files/7921364/Erganzung.in.BARTOC.2.md)
Even though this issue was already closed, I wanted to add the progress i made while still working on it: As a continuation of the actual task, I had started - under agreement with @nichtich  - to transfer the full KOS Registry [click here](https://github.com/gbv/kos-registry/releases/tag/20200521.1941) from cocoda to Bartoc. I didnt finish it, but mabye it will come in handy.

**Comment by stefandesu** [comment]
Thanks @sabrinagaab!
