### ISSUE TITLE
GitHub repository verlinken

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-conc.gbv.de#45]
Von der Hauptseite sollte auf das GitHub repository verlinkt werden. Momentan sind nur die GitHub-Accounts verlinkt.

**Comment by stefandesu** [comment]
Auf welches GitHub-Repository, das der Webseite? Das ist im Footer unter "Source" verlinkt. Man könnte auf die Liste aller Repositories mit Tag "coli-conc" verlinken: https://github.com/search?q=topic%3Acoli-conc+org%3Agbv+fork%3Atrue

**Comment by nichtich** [comment]
Hmmm unter <https://coli-conc.gbv.de/contact/> sollte stehen dass Fragen zur Software auch direkt unter <https://github.com/gbv/cocoda/issues> bzw. unter dem Issue-Tracker einer der anderen Software-Komponenten gestellt werden können.

**Comment by DavidBRohrer** [comment]
Bitte mal drüberschauen. Habe etwas herumgefeilt.

**Comment by stefandesu** [comment]
Ich hab den Text mal weiter nach unten geschoben, ich finde, das sieht etwas besser aus. Sonst super. 👍
