### ISSUE TITLE
Add SWIb 2021 talk

### ISSUE THREAD

**Issue by nichtich** [gbv/coli-conc.gbv.de#52]
Add SWIB 2021 talk to  https://coli-conc.gbv.de/publications/. Requires the final PDF slides (should be published at Zenodo) and the Video recording at TIB AV Portal (will be published there soon).

**Comment by DavidBRohrer** [comment]
Slides are on the site now. 
I'm going to link the video as well when it's published.

**Comment by nichtich** [comment]
https://swib.org/swib21/programme.html contains links to slides and video at YouTube, we can use the same links

**Comment by DavidBRohrer** [comment]
don't know what went wrong with me. I used the links which are on the programms-site now. But the PDF-File seems to be broken.
